authenticate/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.urls import reverse

urlpatterns = [
    path('home/', views.home,name='home'),
    path('signup/', views.signup,name='signup'),
    path('signin/', views.signin,name='signin'),
    path('profile/', views.profile,name='profile'),
    path('signout/', views.signout,name='logout'),
    path('search/', views.search,name='search'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    
    
]
    

bloodbuddy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('authenticate.urls')),
    path('', include('chat.urls'))
]

chat/urls.py
from django.urls import path
from . import views
app_name = 'chat'
urlpatterns = [
    path('chat/', views.chathome, name='chathome'),
    path('<str:room>/', views.room, name='room'),
    path('chat/checkview', views.checkview, name='checkview'),
    path('send', views.send, name='send'),
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),
]

authenticate/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

#created a class Userprofile with instance of User to connect the left info of user in myuser.
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    fullname =models.CharField(max_length=255, blank =False)
    age = models.IntegerField(blank=False)
    address = models.CharField(max_length=255,  blank=False)
    bloodgroup = models.CharField(max_length=5, blank =False)
    gender = models.CharField(max_length=7 , blank =False)
    
    def __str__(self):
        return self.fullname
    
    

authenticate/views.py
from django.core.mail import EmailMessage
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.template.loader import render_to_string 
from django.utils.encoding import force_bytes, force_str
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.forms import AuthenticationForm
from django.core.mail import EmailMultiAlternatives
from django.conf import settings
from . tokens import generate_token
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from .models import UserProfile
import mysql.connector
def home(request):
    return render(request, 'index.html')

def signup(request):
    # Signup form
    if request.method == "POST":
        fullname = request.POST.get("fullname")
        email = request.POST.get("email")
        username = request.POST.get("username")
        bloodgroup = request.POST.get("bloodgroup")
        age = request.POST.get("age")
        address = request.POST.get("address")
        gender = request.POST.get("gender")
        pass1 = request.POST.get("pass1")
        pass2 = request.POST.get("pass2")
        

        # Validate username
        if User.objects.filter(username=username).exists():
            messages.error(request, "Username already exists! Please try a different username.")
            return redirect('home')

        # Validate email
        if User.objects.filter(email=email).exists():
            messages.error(request, "Email already registered!")
            return redirect('home')

        # Validate password
        if pass1 != pass2:
            messages.error(request, "Passwords do not match!")
            return redirect('home')

        reqage = int(age)
        if reqage < 18:
            messages.error(request, "You need to be at least 18 years old")
            return redirect('home')

        # Create user object
        myuser = User.objects.create_user(username, email, pass1)
        myuser.is_active = False
        myuser.save()
        
                         
                    

        # Create UserProfile associate with the User and them adding it to myuser
        UserProfile.objects.create(user=myuser, fullname=fullname, age=age, gender=gender, bloodgroup=bloodgroup, address=address)
        
        # Send welcome email
        subject = "Welcome to Blood Buddy"
        message = f"Hello {myuser.first_name}!\n\n Please confirm your email address to activate your account.\n\nRegards,\nThe Blood Buddy Team"
        send_mail(subject, message, settings.EMAIL_HOST_USER, [myuser.email], fail_silently=True)

        # Send email confirmation link
        current_site = get_current_site(request)
        email_subject = "Confirm Your Email Address"
        message2 = render_to_string('email_confirmation.html', {
            'name': myuser.first_name,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(myuser.pk)),
            'token': generate_token.make_token(myuser)

        })
        email = EmailMessage(
            email_subject,
            message2,
            from_email=settings.EMAIL_HOST_USER,
            to=[myuser.email],
        )
        email.send()
        

        messages.success(request, "Your account has been created successfully! Please check your email to activate your account.")
        return redirect('signin')
    
    return render(request, "signup.html")


def activate(request,uidb64,token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        myuser = User.objects.get(pk=uid)
    except (TypeError,ValueError,OverflowError,User.DoesNotExist):
        myuser = None

    if myuser is not None and generate_token.check_token(myuser,token):
        myuser.is_active = True
        myuser.save()
        login(request,myuser)
        messages.success(request, "Your Account has been activated!!")
        return redirect('signin')
    else:
        return render(request,'activation_failed.html')




def signin(request, signup=None):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        # Authentication successful
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            messages.success(request, 'Successfully signed in!')
            return redirect('profile')
        else:
            messages.error(request, 'Invalid username or password')
            return redirect('home')
        
    return render(request, 'signin.html')


#main profile page
def profile(request):
    if not request.user.is_authenticated:
        messages.error(request, 'You must be logged in first')
        return redirect('home')
    print(request.session.items())
    current_username = request.user.username
    user_profile = UserProfile.objects.get(user=request.user)
    
    return render(request, 'profile.html', {'user_profile': user_profile, 'current_username': current_username})
        
def search(request):
    
    #for searching in search
    if request.method == 'POST':
        srch_bloodgroup = request.POST.get('bloodgroup')
        srch_address = request.POST.get('address')
        person = UserProfile.objects.filter(bloodgroup__icontains=srch_bloodgroup, address__icontains=srch_address)
        return render(request,'search.html',{'person':person})

    return render(request, 'search.html')
    

#logout page
def signout(request):
    logout(request)
    messages.success(request, 'Log out successfully')
    return redirect('home')

authenticate/templates/activation_failed.html.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Activation Failed</title>
</head>
<body>
    <p>We're sorry, but we were unable to activate your account. Please contact support for assistance.</p>
    <p>Best regards,<br>Blood Buddy Team</p>
</body>
</html>

authenticate/templates/email_confirmation.html
{% autoescape off %}
 Hello {{ name }}!!
 Please verify your email by clicking on the following link.
 Confirmation Link: http://{{ domain }}{% url 'activate' uidb64=uid token=token %} 
{% endautoescape %}

authenticate/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        *{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'montserrat', sans-serif;
            margin: 0;
            padding: 0;
        }

        .navbar {
            /* From https://css.glass */
            background: rgba(255, 255, 255, 0.12);
            border-radius: 16px;
            box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
            backdrop-filter: blur(5px);
            -webkit-backdrop-filter: blur(5px);
            border-bottom: 1px solid rgba(0, 0, 0, 0.1); /* Add a border for separation */
            overflow: hidden;
            position: fixed;
            top: 0;
            width: 100%;
            z-index: 1000;
        }
    
        .navbar a {
            float: right; /* Align links to the right */
            display: block;
            color: black;
            text-align: center;
            padding: 20px 16px;
            text-decoration: none;
            font-size: 17px;
            font-weight: bold;
            text-transform: uppercase;
        }
    
        .navbar a:hover {
            background-color: rgba(255, 255, 255, 0.7); /* Add transparency on hover */
            color: black;
        }

        .bgimage {
            background: url("{% static 'bg1.jpg' %}");
            background-size: 100%;
            width: 100%;
            height: 100vh;
            position: relative;
        }

        .menu {
            width: 100%;
            height: 100px;
        }

        .leftmenu {
            width: 25%;
            line-height: 100px;
            float: left;
        }

        .leftmenu h4 {
            padding-left: 20px;
            font-weight: bold;
            color: black;
            font-size: 22px;
        }

        .rightmenu {
            width: 60%;
            height: 100px;
            float: right;
        }

        .rightmenu ul {
            margin-left: 385px;
        }

        .rightmenu ul li {
            display: inline-block;
            list-style: none;
            font-size: 15px;
            color: black;
            font-weight: bold;
            line-height: 100px;
            margin-left: 40px;
            text-transform: uppercase;
            cursor: pointer;
        }

        .rightmenu ul li:hover {
            color: white;
        }

        .rightmenu ul li:visited {
            color: black;
        }

        .text {
            width: 100%;
            margin-top: 185px;
            text-transform: uppercase;
            text-align: center;
            color: black;
        }

        .text h1 {
            font-size: 62px;
            font-family: Georgia, 'Times New Roman', Times, serif;
            font-weight: 700;
            margin: 14px 0;
            text-shadow: 2px 2px 4px #3e403d;
        }

        .text h2 {
            font-size: 20px;
            font-family: Georgia, 'Times New Roman', Times, serif;
            text-shadow: 2px 2px 4px #393a39;
        }

        .btn {
            background-color: rgba(255, 255, 255, 0.164);
            color: black;
            border: none;
            text-decoration: none;
            font-size: 15px;
            font-weight: bold;
            text-transform: uppercase;
            line-height: 40px;
            width: 150px;
            margin-top: 25px;
            border: 3px solid black;
            cursor: pointer;
        }

        button a {
            text-decoration: none;
            color: black;
        }

        .btn:hover {
            background-color: white;
            color: black;
            text-decoration: none;
        }

        img {
            width: 250px;
            position: absolute;
            left: 10px;
            bottom: 30px;
        }

        .message {
            position: right;
        }
        .modal {
            display: none;
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            padding: 20px;
            background: rgba(255, 255, 255, 0.4);
            border-radius: 16px;
            box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
            backdrop-filter: blur(11px);
            -webkit-backdrop-filter: blur(5px);
            z-index: 1001;
        }

        .modal h3 {
            font-size: 18px;
            margin-bottom: 10px;
        }

        .close {
            position: absolute;
            top: 10px;
            right: 10px;
            cursor: pointer;
        }
        p {
            line-height: 1.5;
        }

    </style>
</head>
<body>
    <div class="navbar">
        <a href="#" onclick="showContactDialog()">Contact</a>
        <a href="#" onclick="showAboutUsDialog()">About Us</a>
        <a href="#">Home</a>
    </div>

    <div id="aboutUsModal" class="modal">
        <span class="close" onclick="closeModal('aboutUsModal')">&times;</span>
        <h3>About Us</h3>
        <p>Welcome to Bloodbuddy – Your Lifeline for Blood Connections!<br>
            🩸 Swift Connections: Our advanced algorithms ensure rapid matching of donors with recipients. In moments of urgency, every second counts, and Bloodbuddy is committed to making swift connections to save lives.<br>
            <br>
            👥 Verified Profiles: Safety is paramount. We meticulously verify the profiles of both donors and recipients, creating a secure and trustworthy community dedicated to the noble cause of blood donation.<br>
            <br>
            🤝 Community Support: Beyond a platform, Bloodbuddy is a community of compassionate individuals united by the common goal of saving lives. Our support system goes beyond matches, fostering a sense of solidarity and shared responsibility.<br>
            <br>
            🔒 Privacy and Confidentiality: We understand the sensitivity of the information involved in blood donation. Rest assured, your privacy is our top priority. Bloodbuddy maintains strict confidentiality standards to protect your personal information.</p>
            <br>
    </div>

    <!-- Modal for Contact Us -->
    <div id="contactModal" class="modal">
        <span class="close" onclick="closeModal('contactModal')">&times;</span>
        <h3>Contact Us</h3>
        <p>We value your feedback and inquiries. Reach out to us through the following channels:</p>
        <ul>
            <li><strong>Email:</strong> <a href="mailto:info@bloodbuddy.com">info@bloodbuddy.com</a></li>
            <li><strong>Phone:</strong> +977 9845000000</li>
            <li><strong>Address:</strong> Bloodbuddy Headquarters, Pokhara , Nepal</li>
        </ul>
        <br>
        <p>We're here to assist you. Your suggestions are important to us as we strive to improve and make a positive impact on the community.</p>
    </div>

    <div class="bgimage">
        <div class="menu">
            <div class="leftmenu">
                <h4><img src="{% static 'childbuddy.png' %}" alt=""> </h4>
            </div>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>

        <div class="text">
            <h2> WELCOME TO </h2>
            <h1> BLOODBUDDY </h1>

            <button class="btn"><a href="{% url 'signin' %}"> SIGN IN </a></button> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <button class="btn"><a href="{% url 'signup' %}"> SIGN UP </a></button>
        </div>
    </div>

    <script>
        function showAboutUsDialog() {
            document.getElementById('aboutUsModal').style.display = 'block';
        }

        function showContactDialog() {
            document.getElementById('contactModal').style.display = 'block';
        }

        function closeModal(modalId) {
            document.getElementById(modalId).style.display = 'none';
        }
    </script>
</body>
</html>

authenticate/templates/profile.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <style>
        body {
            margin: 0;
            font-family: 'Arial', sans-serif;
            background: linear-gradient(to right, #FF6B6B, #FF8E53);
            color: white;
            overflow-x: hidden;
        }

        header {
            background: transparent;
            box-shadow: none;
            position: relative;
        }

        .navbar {
            overflow: hidden;
            /* From https://css.glass */
            background: rgba(255, 255, 255, 0.24);
            border-radius: 7px;
            box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
            backdrop-filter: blur(7px);
            -webkit-backdrop-filter: blur(7px);
            border: 1px solid rgba(255, 255, 255, 0.3);
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 10px;
        }

        .navbar a {
            font-size: 16px;
            color: white;
            text-align: center;
            text-decoration: none;
            padding: 10px;
            transition: color 0.3s;
            cursor: pointer;
        }

        .navbar a:hover {
            color: #ddd;
        }

        .logout-btn {
            background-color: #d9534f;
            color: white;
            border: none;
            padding: 10px 15px;
            font-size: 16px;
            cursor: pointer;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .logout-btn:hover {
            background-color: #c9302c;
        }

        .container {
            margin: 20px auto;
            max-width: 600px;
            background: rgba(255, 255, 255, 0.04);
            border-radius: 16px;
            box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
            backdrop-filter: blur(5px);
            -webkit-backdrop-filter: blur(5px);
            border: 1px solid rgba(255, 255, 255, 0.3);           
             border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            padding: 20px;
            transition: box-shadow 0.3s, background-color 0.3s;
        }

        .container:hover {
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.2);
            background-color: rgba(255, 255, 255, 0.1);
        }

        h2 {
            color: #1877f2;
            text-align: center;
            margin-bottom: 10px;
        }

        .profile-details {
            text-align: center;
            margin-top: 20px;
        }

        .profile-details p {
            margin: 10px 0;
            color: #333;
        }

        .arrow-btn {
            background-color: transparent;
            color: white;
            border: none;
            cursor: pointer;
            font-size: 16px;
            transition: color 0.3s;
        }

        .arrow-btn:hover {
            color: #ccc;
        }

        .material-symbols-outlined {
            color: white;
            font-variation-settings:
                'FILL' 0,
                'wght' 500,
                'GRAD' 0,
                'opsz' 29;
        }

    </style>
</head>

<body>
    <header>
        <div class="navbar">
            <a href="{% url 'search' %}" onclick="scrollToSection('search-section')">
                <span class="material-symbols-outlined">search</span>
            </a>
            <button class="logout-btn" onclick="logout()">Logout</button>
        </div>
    </header>

    <div class="container" id="search-section">
        <h2>Welcome, {{ current_username }}!</h2>

        <!-- Display user details -->
        <div class="profile-details">
            <p><strong>Username:</strong> {{ current_username }}</p>
            <p><strong>Address:</strong> {{ user_profile.address }}</p>
            <p><strong>Age:</strong> {{ user_profile.age }}</p>
            <p><strong>Bloodgroup:</strong> {{ user_profile.bloodgroup }}</p>
            <p><strong>Gender:</strong> {{ user_profile.gender }}</p>
        </div>
    </div>

    <script>
        function scrollToSection(sectionId) {
            const section = document.getElementById(sectionId);
            section.scrollIntoView({ behavior: 'smooth' });
        }

        function logout() {
            // Redirect to logout URL
            window.location.href = "{% url 'logout' %}";
        }
    </script>
</body>

</html>

authenticate/templates/search.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Results</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f0f0f0;
            color: #333;
            transition: background-color 0.5s ease;
        }

        header {
            background: rgba(255, 255, 255, 0.8);
            border-radius: 16px;
            box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
            backdrop-filter: blur(11px);
            -webkit-backdrop-filter: blur(5px);
            z-index: 1001;
            padding: 20px;
            color: #444;
            text-align: center;
            transition: background-color 0.5s ease;
        }

        form {
            margin-bottom: 20px;
            text-align: center;
        }

        label {
            margin-right: 10px;
            color: #555;
        }

        select,
        button {
            padding: 12px;
            margin: 5px;
            border: none;
            border-radius: 8px;
            font-size: 16px;
            transition: background-color 0.2s ease, color 0.2s ease, transform 0.1s ease;
        }

        select:hover,
        button:hover {
        background: rgba(255, 28, 28, 0.26);
        border-radius: 16px;
        box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
        backdrop-filter: blur(13.6px);
        -webkit-backdrop-filter: blur(13.6px);
        border: 1px solid rgba(255, 28, 28, 0.3);
            color: #fff;
            cursor: pointer;
            transform: scale(1.05);
        }

        h1 {
            text-align: center;
            color: #333;
            margin-bottom: 20px;
        }

        ul {
            list-style: none;
            padding: 0;
            margin: 0;
        }

        li {
            background-color: #fff;
            margin: 20px;
            padding: 25px;
            border-radius: 12px;
            box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
            transition: transform 0.3s ease;
        }

        li:hover {
            transform: scale(1.02);
        }

        strong {
            font-weight: bold;
        }

        .profile-box,
        .message-box {
            text-align: center;
            margin-top: 20px;
        }

        .profile-box a,
        .message-box a {
            display: inline-block;
            padding: 15px 30px;
            border-radius: 12px;
            background-color:   #ff4d94;
            color: #fff;
            text-decoration: none;
            margin: 10px;
            transition: background-color 0.3s ease, color 0.3s ease, transform 0.2s ease;
        }

        .profile-box a:hover,
        .message-box a:hover {
        background: rgba(255, 77, 148, 1);
        border-radius: 16px;
        box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
        backdrop-filter: blur(13.6px);
        -webkit-backdrop-filter: blur(13.6px);
        border: 1px solid rgba(255, 77, 148, 0.3);
            transform: scale(1.05);
        }

        .profile-box {
            float: left;
        }

        .message-box {
            float: right;
        }

        .clearfix::after {
            content: "";
            clear: both;
            display: table;
        }
    </style>
</head>

<body>

    <header>

        <!-- Your search form here -->
        <form method="post" action="">
            {% csrf_token %}

            <label for="bloodgroup">Blood Group:</label>
            <select id="bloodgroup" name="bloodgroup" required>
                <option value="" disabled selected>Select Blood Group</option>
                <option value="A+">A+</option>
                <option value="A-">A-</option>
                <option value="B+">B+</option>
                <option value="B-">B-</option>
                <option value="AB+">AB+</option>
                <option value="AB-">AB-</option>
                <option value="O+">O+</option>
                <option value="O-">O-</option>
            </select>

            <label for="address">Address:</label>
            <select id="address" name="address" required>
                <option value="" disabled selected>Select Province</option>
                <option value="koshi">Koshi Province (कोशी प्रदेश)</option>
                <option value="madhesh">Madhesh Province (मधेस प्रदेश)</option>
                <option value="bagmati">Bagmati Province (बाग्मती प्रदेश)</option>
                <option value="gandaki">Gandaki Province (गण्डकी प्रदेश)</option>
                <option value="lumbini">Lumbini Province (लुम्बिनी प्रदेश)</option>
                <option value="karnali">Karnali Province (कर्णाली प्रदेश)</option>
                <option value="sudurpashchim">Sudurpashchim Province(सुदूरपश्चिम प्रदेश)</option>
            </select>
            <button type="submit">Search</button>
        </form>
    </header>

    <h1>Search Results</h1>

    {% if person %}
    <ul>
        {% for p in person %}
        <li>
            <strong>Name:</strong> {{ p.fullname }}<br>
            <strong>Age:</strong> {{ p.bloodgroup }}<br>
            <strong>Address:</strong> {{ p.address }}<br>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No users found.</p>
    {% endif %}

    <div class="clearfix"></div>

    <div class="profile-box">
        <a href="{% url 'profile' %}">Profile</a>
    </div>

    <div class="message-box">
        <a href="{% url 'chat:chathome' %}">Message</a>
    </div>

</body>

</html>

authenticate/templates/signin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign In in BloodBuddy</title>
    <style>
        *{
            box-sizing: border-box;
            align-content: stretch;

        }
        html,body{
            height: 100%;
        }
        body{
            font-family: Georgia, 'Times New Roman', Times, serif;
            margin: 20px 435px;
            font-size: 17px;
            padding: 10px;
           /* overflow: hidden;   it makes the scroll bar disappear */
           
        }

        
        .background{
            background-image: url("/static/bloodyhell.png");
            height: 100%;
            background-position: center;
            background-color: #e0cfcf;
            background-repeat: no-repeat;   /*as the background picture of ours doesnt really cover te whole background,,, repeating it in x-axis would make it look better*/
            background-size: cover;
            display: block;
            text-align: center;   /*display and text-align helps you to bring the form below in centre*/
            
            
            
        }
        .whole{
            padding: 10px;
            border: 1px solid black;
            border-radius: 5px;
            box-shadow: 12px 12px 2px 1px rgba(37, 37, 38, 0.2);
            text-shadow: 2px 2px 4px #3e403d;
            background-color: rgba(255, 255, 255, 0.441);
            background: rgba(255, 255, 255, 0.18);
            border-radius: 16px;
            box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
            backdrop-filter: blur(6px);
            -webkit-backdrop-filter: blur(5px);
        }

       
        




        input[type="text"],
        input[type="password"]{
            border: 1px solid black;
            line-height: 1em;
        }
        input[type="text"],
        label,
        input[type="password"]{
            width: 75%;
            padding: 12px;
            
            border-radius: 4px;
            border-color: rgb(12, 75, 130);
            text-align: !important left ;
        }
       input[type="submit"]{
        width: 25%;
        background-color: red;
        padding: 12px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
       }
       input[type="submit"]:hover{
        background-color:rgba(255, 255, 255, 0.56);
        box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
        backdrop-filter: blur(10.2px);
                -webkit-backdrop-filter: blur(10.2px);
                border: 1px solid rgba(255, 255, 255, 1);
                color: black;
       }
       input[type="submit"]:visited{
        background-color: #1d10d6;
       }
       .img{
        height: 100px;
        width: 100px;
        clip-path: circle(50% at 50% 50%);
       }
       a{
        color: black;
       }
       img.bloodbuddy{
       animation: bouncing 0.5s ease-out 1s infinite alternate both;
       width: 80px;
       position: absolute;
       left: 0px;
       bottom: 0px;
       }
       @keyframes bouncing {
            0%{
                bottom: 0;
                
            }
            100%{
                bottom: 50px;
                
            }
            
        }
       
    </style>
</head>
<body class="background">
    <div class="mole"></div>
    <div class="whole">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
        <form action="/signin/" method="post" class="form">
            {% csrf_token %}
            <img src="{% static 'blood buddy.png' %}" class="bloodbuddy" alt="">
            <header>
            <img class="img" src="/static/userimage.png" alt="this is user image">
            <h1>Sign In</h1>
            </header>
            <p>Username</p><input type="text" name="username" id="username" required>
            <p>Password</p><input type="password" name="password" id="password" required>
            <br>
            <label for="checkbox"><input id="checkbox"  type="checkbox" value="test" />Remember me</label>
            <br>
            <br>
            <input type="submit"value="Sign In" style="font-size: 16px;">
            <br>
            <br>
            <a href="{% url 'signup' %}">Don't have an account?</a>
            <br>
            <br>
        </form>
    </div>
    
</body>
</html>